# Конфигурация развертывания на Render.com
services:
  - type: web
    name: web-service-lab1
    env: python
    plan: free
    python:
      version: "3.11.8"
    # Установка зависимостей
    buildCommand: pip install -r requirements.txt
    # Запуск
    startCommand: cd flaskapp && gunicorn wsgi:app -b 0.0.0.0:$PORT
    envVars:
      # Render автоматически сгенерирует безопасный SECRET_KEY
      - key: SECRET_KEY
        generateValue: true
      # Добавляем reCAPTCHA ключи как environment variables
      - key: RECAPTCHA_PUBLIC_KEY
        value: '6LfXBgksAAAAAIHzKu-_MNePxVi9Z67Z_ZZOiV9F'
      - key: RECAPTCHA_PRIVATE_KEY  
        value: '6LfXBgksAAAAAEK2_3jlgo5_o304LE6yhbpSCxxs'
